apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deployment
  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
        - name: backend-get
          image: public.ecr.aws/c5h0b4m1/awslinux:get
          imagePullPolicy:Always
          ports:
            - containerPort: 5000

            